openapi: 3.0.0
info:
  title: Fitness App Api
  description: Api for fitness app
  version: 0.0.1
servers:
  - url: 'https://crossfit-api-2020.herokuapp.com/'
    description: Test server
paths:
  /api/v1/exercises/:
    post:
      summary: Exercise creation
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeaderParameter'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExerciseCreationBody'
      responses:
        '200':
          description: json with created exercise info or json with message when error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExerciseCreationEditingSuccessResponse'
    get:
      summary: Get list of exercises
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeaderParameter'
        - $ref: '#/components/parameters/UserIdUrlParameter'
      responses:
        '200':
          description: Json with list of exercises of user with id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExerciseGetListResponse'
  '/api/v1/exercises/{id}':
    get:
      summary: Get info about exercise
      parameters:
        - $ref: '#/components/parameters/IdPathParameter'
        - $ref: '#/components/parameters/AuthorizationHeaderParameter'
      responses:
        '200':
          description: return info aboun exercise
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExerciseGetInfoResponse'
    put:
      summary: Used to edit exercise. Body required only fields that needs change
      parameters:
        - $ref: '#/components/parameters/IdPathParameter'
        - $ref: '#/components/parameters/AuthorizationHeaderParameter'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExerciseEditingBody'
      responses:
        '200':
          description: Return info about exercises
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExerciseCreationEditingSuccessResponse'
  /api/v1/trainings:
    post:
      summary: Create training
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeaderParameter'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTrainingBody'
      responses:
        '200':
          description: 'Ok, training created'
components:
  schemas:
    UserRegistrationBody:
      title: Register Body
      description: Body when register user
      type: object
      properties:
        trainer:
          type: string
          enum:
            - trainer
        email:
          type: string
          pattern: '^[^@\s]+@[^@\s\.]+\.[^@\.\s]+$'
        password:
          type: string
        password_confirmation:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        phone:
          type: string
      required:
        - trainer
        - email
        - password
        - password_confirmation
    UserRegistrationResponseOk:
      type: object
      properties:
        message:
          type: string
        user_id:
          type: number
      required:
        - message
        - user_id
    UserRegistrationResponseOtherError:
      type: object
      properties:
        message:
          type: string
        user_id:
          type: string
          enum:
            - null
      required:
        - message
        - user_id
    UserRegistrationResponseErrorWithMessage:
      type: object
      properties:
        message:
          type: string
          enum:
            - User exist
      required:
        - message
    UserLoginByPassword:
      type: object
      properties:
        grant_type:
          type: string
          enum:
            - password
        email:
          type: string
          pattern: '^[^@\s]+@[^@\s\.]+\.[^@\.\s]+$'
        password:
          type: string
      required:
        - grant_type
        - email
        - password
    UserLoginSuccessResponse:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
          enum:
            - bearer
        expires_in:
          type: number
        created_at:
          type: number
        user_id:
          type: number
        trainer:
          type: boolean
        client:
          type: boolean
      required:
        - access_token
        - user_id
    UserGetInfoResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
            attribures:
              type: object
              properties:
                email:
                  type: string
                first-name:
                  type: string
                  nullable: true
                last-name:
                  type: string
                  nullable: true
                phone:
                  type: string
                  nullable: true
              required:
                - email
                - first-name
                - last-name
                - phone
          required:
            - id
            - attributes
      required:
        - data
    UserPusInfoResponse:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        phone:
          type: string
          nullable: true
      required:
        - id
        - email
        - first_name
        - last_name
        - phone
    ErrorResponseWithMessage:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    ExerciseCreationBody:
      description: Json body to use when create exercise
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        videoUrl:
          type: string
        equipment:
          type: string
        user_id:
          type: string
      required:
        - name
        - user_id
    ExerciseEditingBody:
      description: Json body to use when update(put) exercise. Required at most one parameter to edit
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        videoUrl:
          type: string
        equipment:
          type: string
    ExerciseCreationEditingSuccessResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
          nullable: true
        videoUrl:
          type: string
          nullable: true
        equipment:
          type: string
          nullable: true
        created_at:
          type: string
        updated_at:
          type: string
      required:
        - id
        - name
        - description
        - videoUrl
        - equipment
        - created_at
        - updated_at
    ExerciseGetInfoResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
            attribures:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                  nullable: true
                video-url:
                  type: string
                  nullable: true
                equipment:
                  type: string
                  nullable: true
              required:
                - name
                - description
                - video-url
                - equipment
          required:
            - id
            - attributes
      required:
        - data
    ExerciseGetListResponse:
      type: object
      properties:
        message:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
                nullable: true
              description:
                type: string
                nullable: true
              videoUrl:
                type: string
                nullable: true
              equipment:
                type: string
                nullable: true
              user_id:
                type: string
                nullable: true
            required:
              - name
              - description
              - videoUrl
              - equipment
              - user_id
      required:
        - message
    CreateTrainingBody:
      type: object
      required:
        - name
        - trainer_id
        - start_time
        - description
        - sections
      properties:
        name:
          type: string
        trainer_id:
          type: string
        start_time:
          type: string
        description:
          type: string
        sections:
          type: array
          items:
            $ref: '#/components/schemas/TrainingSection'
    TrainingSection:
      oneOf:
        - $ref: '#/components/schemas/EmomTrainingSection'
        - $ref: '#/components/schemas/RestTrainingSection'
        - $ref: '#/components/schemas/AmrapOrForTimeTrainingSection'
      discriminator:
        propertyName: section_type
        mapping:
          EMOM: '#/components/schemas/EmomTrainingSection'
          REST: '#/components/schemas/RestTrainingSection'
          AMRAP: '#/components/schemas/AmrapOrForTimeTrainingSection'
          FOR_TIME: '#/components/schemas/AmrapOrForTimeTrainingSection'
    EmomTrainingSection:
      type: object
      required:
        - section_type
        - start_minute
        - duration
      properties:
        section_type:
          type: string
        duration:
          type: number
        start_minute:
          type: number
        actions:
          type: array
          items:
            type: object
            required:
              - exercise_id
              - minute
            properties:
              default_value_man:
                type: number
              default_value_woman:
                type: number
              distance:
                type: number
              profile_index:
                type: string
              reps:
                type: integer
              exercise_id:
                type: integer
              minute:
                type: integer
              ratio:
                type: integer
    RestTrainingSection:
      type: object
      required:
        - section_type
        - start_minute
        - duration
      properties:
        section_type:
          type: string
        duration:
          type: number
        start_minute:
          type: number
    AmrapOrForTimeTrainingSection:
      type: object
      required:
        - section_type
        - start_minute
        - duration
      properties:
        section_type:
          type: string
        duration:
          type: number
        start_minute:
          type: number
        actions:
          type: array
          items:
            type: object
            required:
              - exercise_id
            properties:
              default_value_man:
                type: number
              default_value_woman:
                type: number
              distance:
                type: number
              profile_index:
                type: string
              reps:
                type: integer
              exercise_id:
                type: integer
              ratio:
                type: integer
  examples:
    UserAsTrainerRegistrationDataExample:
      value:
        trainer: trainer
        email: someMail@gmail.com
        password: '12345678'
        password_confirmation: '12345678'
      summary: Example user
    UserLoginRequestExample:
      value:
        grant_type: password
        email: someMail@gmail.com
        password: '12345678'
    UserGetInfoResponseExample:
      value:
        data:
          id: '80'
          type: users
          attributes:
            email: somemail@gmail.com
            first-name: lag1
            last-name: agl1
            phone: null
    ExerciseCreateionRequiestExample:
      value:
        name: Exercise 4
    ExerciseCreateionResponseExample:
      value:
        id: 4
        name: Exercise 3
        description: Description
        videoUrl: 'http://google.com'
        equipment: equipment
        created_at: '2020-09-04T22:10:15.027+03:00'
        updated_at: '2020-09-04T22:10:15.027+03:00'
  parameters:
    IdPathParameter:
      name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
        format: int64
    AuthorizationHeaderParameter:
      name: authorization
      in: header
      description: 'value should be bearer: #{token_id}'
      required: true
      schema:
        type: string
    UserIdUrlParameter:
      name: user_id
      in: query
      schema:
        type: integer
      description: Id of user
